name: Deploy Saferut
#main-
on:
  push:
    branches: [ "main" ]
      
jobs:   
  deploy_ovh_primary:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
        #Deploy
      - name: Deploy to master folder
        run: rsync -avz --exclude={.git,.github} ./ /home/ubuntu/fastapi_task_manager/
      - name: Navigate to root directory
        run: cd /home/ubuntu/fastapi_task_manager
      - name: Install venv
        run: python3 -m venv venv
        #ajusta path and install requeriments
      - name: using venv
        run: | 
          source venv/bin/activate
          pip install -r requirements.txt
        #desactivate venv
      - name: Deactivate venv
        run: deactivate
